export const GRAPHQL_STATUS = { SUCCESS: 'SUCCESS', ERROR: 'ERROR' };
export const CAR_SIZE = { S: 'S', M: 'M', L: 'L', X: 'X' };
export const SLOT_STATUS = { AVAILABLE: 'AVAILABLE', UNAVAILABLE: 'UNAVAILABLE' };

export const ERROR_CODE = {
  CREATE_PARKING_LOT_FAIL: 'CREATE_PARKING_LOT_FAIL',
  DUPLICATE_PARKING_ON_FLOOR: 'DUPLICATE_PARKING_ON_FLOOR',
  PARK_THE_CAR_FAIL: 'PARK_THE_CAR_FAIL',
  LEAVE_THE_SLOT_FAIL: 'LEAVE_THE_SLOT_FAIL',
  PARKING_NOT_AVAILABLE: 'PARKING_NOT_AVAILABLE',
  DUPLICATE_PLATE_NUMBER: 'DUPLICATE_PLATE_NUMBER',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  GET_STATUS_OF_PARKING_FAIL: 'GET_STATUS_OF_PARKING_FAIL',
  GET_REGISTRATION_ALLOCATED_SLOT_BY_CAR_FAIL: 'GET_REGISTRATION_ALLOCATED_SLOT_BY_CAR_FAIL',
  GET_REGISTRATION_PLATE_NUMBER_BY_CAR_FAIL: 'GET_REGISTRATION_PLATE_NUMBER_BY_CAR_FAIL'
};
